[package]
name = "projektor"
version = "0.1.0"
description = "Tui application for keeping track of Git repositories and Personal Projects."
authors = ["Florian Gassmann <flo.gassmann53@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.30.0"
color-eyre = "0.6.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.0"
tui-markdown = { version = "0.3.7",default-features = false, features = []}
ratatui-textarea = "0.9.1"
ratatui-explorer = "=0.3.0"
clap = { version = "4.6.6", features = ["derive"] }

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true


[profile.profiling]
inherits = "dev"
opt-level = 1
debug = true
